--GERA OS COMANDOS PARA A DESFRAGMENTACAO

DECLARE @VDATABASE VARCHAR(255)
DECLARE @VTABLE VARCHAR(255)
DECLARE @VINDEX VARCHAR(255)
DECLARE @VFRAGMENT VARCHAR(255)
DECLARE @VFILLFACTOR INT
DECLARE @CMD VARCHAR(MAX)
DECLARE @MIN INT
DECLARE @MAX INT

SET @VFILLFACTOR = 80

-- SELECIONA OS REGISTROS

IF OBJECT_ID ('TEMPDB..##INDEX_DEFRAG') IS NOT NULL
DROP TABLE ##INDEX_DEFRAG;

SELECT		IDENTITY(INT, 1,1) ID
			, DB_NAME() [DATABASE]
			, SC.name [SCHEMA_NAME]
			, OBJECT_NAME(S.[OBJECT_ID]) [TABELA] 
			, I.NAME [INDICE] 
			, ROUND(AVG_FRAGMENTATION_IN_PERCENT,0) [FRAGMENTACAO]
			, CASE WHEN ROUND(AVG_FRAGMENTATION_IN_PERCENT,0) > 30 THEN 
			'ALTER INDEX [' + I.NAME + '] ON [' + SC.name + '].[' + OBJECT_NAME(S.[OBJECT_ID]) + '] REBUILD WITH (FILLFACTOR = ' + CONVERT(VARCHAR(3), @VFILLFACTOR) + ')' + CHAR(10) + 'GO'
			ELSE 
			'DBCC INDEXDEFRAG ([' + DB_NAME() + '], ''' + SC.name + '.' + OBJECT_NAME(S.[OBJECT_ID]) + ''', [' + I.NAME + '])' + CHAR(10) + 'GO'
			END CMD
INTO ##INDEX_DEFRAG
FROM		SYS.DM_DB_INDEX_PHYSICAL_STATS(DB_ID(),NULL, NULL, NULL, NULL) S 
INNER JOIN	SYS.INDEXES I WITH(NOLOCK) 
ON			S.[OBJECT_ID] = I.[OBJECT_ID] AND S.INDEX_ID = I.INDEX_ID 
INNER JOIN	SYS.objects O WITH(NOLOCK)
ON			O.object_id = I.[OBJECT_ID] 
INNER JOIN	SYS.schemas SC WITH(NOLOCK)
ON			O.schema_id = SC.schema_id
WHERE		I.NAME IS NOT NULL 
--and o.name in ('TB_Cliente',
--'TB_AreaVenda',
--'TB_Canal',
--'TB_OrgVenda',
--'TB_GrupoConta',
--'TB_Empregado')
ORDER BY	ROUND(AVG_FRAGMENTATION_IN_PERCENT,2) DESC



-- RECUPERA MENOR E MAIOR VALOR 
SELECT @MIN = MIN(ID), @MAX = MAX(ID)
FROM ##INDEX_DEFRAG

-- EXECUTA SCRIPTS
WHILE @MIN <= @MAX 

BEGIN 

	SELECT @CMD = CMD
	FROM ##INDEX_DEFRAG
	WHERE ID = @MIN

	--EXEC(@CMD)
	print @CMD
	SET @MIN = @MIN + 1

END