
DROP TABLE IF EXISTS SGBODS.SCH_ODS.TB_VBRK 

CREATE TABLE SGBODS.SCH_ODS.TB_VBRK 
(
VBELN VARCHAR(200)
,FKDAT VARCHAR(200)
,SFAKN VARCHAR(200)
,FKART VARCHAR(200)
,ERDAT VARCHAR(200)
)

--SELECT * FROM SGBODS.SCH_ODS.TB_VBRK 

--DROP TABLE IF EXISTS SGBODS.SCH_ODS.TB_VBRP

--CREATE TABLE SGBODS.SCH_ODS.TB_VBRP
--(
--VBELN VARCHAR(200)
--,POSNR VARCHAR(200)
--,NTGEW VARCHAR(200)
--,AUBEL VARCHAR(200)
--,AUPOS VARCHAR(200)
--,PRSDT VARCHAR(200)
----,PKUNRE VARCHAR(200)
--)

--DROP TABLE IF EXISTS SGBODS.SCH_ODS.TB_J_1BNFDOC

--CREATE TABLE SGBODS.SCH_ODS.TB_J_1BNFDOC
--(
--DOCNUM VARCHAR(200)
--,CANCEL VARCHAR(200)
--,PSTDAT VARCHAR(200)
--)

SELECT * FROM SGBODS.SCH_ODS.TB_J_1BNFLIN

DROP TABLE IF EXISTS SGBODS.SCH_ODS.TB_J_1BNFLIN

CREATE TABLE SGBODS.SCH_ODS.TB_J_1BNFLIN
(
REFKEY VARCHAR(200)
,DOCNUM VARCHAR(200)
,REFITM VARCHAR(200)
)

--NF_DS01-DOCNUM ::: J_1BNFDOC-DOCNUM
--NF_DS01-CANCEL ::: J_1BNFDOC-CANCEL
--NF_DS02-REFKEY ::: J_1BNFLIN-REFKEY
--NF_DS02-DOCNUM ::: J_1BNFLIN-DOCNUM
--NF_DS02-REFITM ::: J_1BNFLIN-REFITM

DROP TABLE IF EXISTS SGBODS.SCH_ODS.TB_MO_PR_CFTH

CREATE TABLE SGBODS.SCH_ODS.TB_MO_PR_CFTH
(
SOCNR VARCHAR(200)
,VBELN VARCHAR(200)
,POSNR VARCHAR(200)
,ERDAT VARCHAR(200)
,ERZET VARCHAR(200)
)

SELECT * 
FROM SGBODS.SCH_ODS.TB_MO_PR_CFTH

--ZDA_SD018-VBELN  ::: /ICO/MO_PR_CFTH-VBELN
--ZDA_SD018-POSNR ::: /ICO/MO_PR_CFTH-POSNR   
--ZDA_SD018-ERZET :::: /ICO/MO_PR_CFTH-ERZET

--ZDA_SD018-SEQNR ::: OIISOCIKN-SEQNR
--ZDA_SD018-KUNNR :::: OIISOCIKN-KUNNR
--ZDA_SD018-SOCNR :::: OIISOCK-SOCNR


DROP TABLE IF EXISTS SGBODS.SCH_ODS.TB_VBUP

CREATE TABLE SGBODS.SCH_ODS.TB_VBUP
(
VBELN VARCHAR(200)
,POSNR VARCHAR(200)
,ABSTA VARCHAR(200)
)

DROP TABLE IF EXISTS SGBODS.SCH_ODS.TB_VBAP

CREATE TABLE SGBODS.SCH_ODS.TB_VBAP
(
ROUTE VARCHAR(200)
,SPART VARCHAR(200)
,PSTYV VARCHAR(200)
,ERNAM VARCHAR(200)
,MATNR VARCHAR(200)
,VBELN VARCHAR(200)
,POSNR VARCHAR(200)
,ERDAT VARCHAR(200)
--,PKUNWE VARCHAR(200)
)

SELECT * FROM SGBODS.SCH_ODS.TB_VBAP

SELECT * FROM SGBODS.SCH_ODS.TB_VBAP

SELECT  DOCNUM
FROM SGBODS.SCH_ODS.TB_J_1BNFDOC NF
INNER JOIN c
ON NF.DOCNUM = OV.VBELN
GROUP BY DOCNUM


DROP TABLE IF EXISTS SGBODS.SCH_ODS.TB_ZSD_STATUS_ORDEM

CREATE TABLE SGBODS.SCH_ODS.TB_ZSD_STATUS_ORDEM
(
VBELN VARCHAR(200)
,STATUS VARCHAR(200)
,DATUM VARCHAR(200)
)

DROP TABLE IF EXISTS SGBODS.SCH_ODS.TB_VBAK

CREATE TABLE SGBODS.SCH_ODS.TB_VBAK
(
VDATU VARCHAR(200)
,KUNNR VARCHAR(200)
,VBELN VARCHAR(200)
,ERDAT VARCHAR(200)
)



SELECT fat_agrd.VBELN
FROM SGBODS.SCH_ODS.TB_VBAP OVC_Agrd  WITH(NOLOCK) -- TransacaoOrdemVendaCab_AGRD

inner join SGBODS.SCH_ODS.TB_VBRP fat_agrd -- TB_TransacaoFatura_Agrd

on OVC_Agrd.VBELN = fat_agrd.AUBEL

and  OVC_Agrd.POSNR = fat_agrd.AUPOS

INNER JOIN SGBODS.SCH_ODS.TB_VBRK FAT_CAB -- TB_TransacaoFaturaCab_Agrd

on fat_agrd.VBELN = FAT_CAB.VBELN	

AND FAT_CAB.FKART not in('FAS','IGS','IVS','LGS','LRS','S1','S2','S3','SHR','S4','S5')

GROUP BY fat_agrd.VBELN

--SELECT * FROM SGBODS.SCH_ODS.TB_VBRP

--TRUNCATE TABLE SGBODS.SCH_ODS.TB_J_1BNFLIN

SELECT DOCNUM 
FROM SGBODS.SCH_ODS.TB_J_1BNFDOC
GROUP BY DOCNUM

SELECT COUNT(1) FROM SGBODS.SCH_ODS.TB_TransacaoNotaFiscal_Agrd Nota
WHERE EXISTS (
SELECT DOCNUM 
FROM SGBODS.SCH_ODS.TB_J_1BNFDOC WITH(NOLOCK)
WHERE DOCNUM = CodDoc
)

SELECT *
FROM SGBODS.SCH_ODS.TB_J_1BNFLIN
WHERE DOCNUM = '0029918262'

SELECT 
Nota.NomRefDocOrigem REFKEY
,Nota.CodDoc DOCNUM
,Nota.CodItemRefOrigem REFITM

FROM SGBODS.SCH_ODS.TB_TransacaoNotaFiscal_Agrd Nota

INNER JOIN SGBODS.SCH_ODS.TB_TransacaoNotaFiscalCab_Agrd CabNota

on Nota.CodDoc = CabNota.CodDoc
and year(CabNota.DthDocumento) = 2022

WHERE NomRefDocOrigem = '9026440803'