use SGBODS
go

--select S.name + '.' + T.name 
--from sys.tables t, sys.schemas s
--where t.schema_id = s.schema_id
--and s.name = 'pm'

select 'USH02' Tabela,  count(1) TOTAL_REGISTROS FROM  sgbods.pm.USH02
UNION ALL
select 'TVLST' Tabela, count(1) TOTAL_REGISTROS FROM  sgbods.pm.TVLST
UNION ALL
select 'TVLKT' Tabela, count(1) TOTAL_REGISTROS FROM  sgbods.pm.TVLKT
UNION ALL
select 'TVKO' Tabela, count(1) TOTAL_REGISTROS FROM  sgbods.pm.TVKO
UNION ALL
select 'TVFKT' Tabela, count(1) TOTAL_REGISTROS FROM  sgbods.pm.TVFKT
UNION ALL
select 'TVAPT' Tabela, count(1) TOTAL_REGISTROS FROM  sgbods.pm.TVAPT
UNION ALL
select 'TVAKT' Tabela, count(1) TOTAL_REGISTROS FROM  sgbods.pm.TVAKT
UNION ALL
select 'TCURR' Tabela, count(1) TOTAL_REGISTROS FROM  sgbods.pm.TCURR
UNION ALL
select 'TBSLT' Tabela, count(1) TOTAL_REGISTROS FROM  sgbods.pm.TBSLT
UNION ALL
select 'TBSL' Tabela, count(1) TOTAL_REGISTROS FROM  sgbods.pm.TBSL
UNION ALL
select 'T179T' Tabela, count(1) TOTAL_REGISTROS FROM  sgbods.pm.T179T
UNION ALL
select 'KNB1' Tabela, count(1) TOTAL_REGISTROS FROM  sgbods.pm.KNB1
UNION ALL
select 'KNA1' Tabela, count(1) TOTAL_REGISTROS FROM  sgbods.pm.KNA1
UNION ALL
select 'MARA' Tabela, count(1) TOTAL_REGISTROS FROM  sgbods.pm.MARA
UNION ALL
select 'MARC' Tabela, count(1) TOTAL_REGISTROS FROM  sgbods.pm.MARC
UNION ALL
select 'USR02' Tabela, count(1) TOTAL_REGISTROS FROM  sgbods.pm.USR02
UNION ALL
select 'TVZBT' Tabela, count(1) TOTAL_REGISTROS FROM  sgbods.pm.TVZBT



if object_id('tempdb..#tmpPM') is not null
drop table #tmpPM
go

select * 

into #tmpPM

from 

(

SELECT 'VBFA' Tabela, left(ERDAT,6) ANOMES , COUNT(1) TOTAL_REGISTROS FROM SGBODS.pm.VBFA GROUP BY left(ERDAT,6) -- ERDAT LIKE '202101%'
UNION ALL
SELECT 'VBKD' Tabela, left(PRSDT,6) ANOMES , COUNT(1) TOTAL_REGISTROS  FROM SGBODS.pm.VBKD GROUP BY left(PRSDT,6)-- PRSDT LIKE '202102%'
UNION ALL
SELECT 'VBEP' Tabela, left(EDATU,6) ANOMES , COUNT(1) TOTAL_REGISTROS FROM SGBODS.pm.VBEP GROUP BY left(EDATU,6) -- EDATU LIKE '202101%'
UNION ALL
SELECT 'VBRK' Tabela, left(ERDAT,6) ANOMES , COUNT(1) TOTAL_REGISTROS FROM SGBODS.pm.VBRK GROUP BY left(ERDAT,6) -- ERDAT LIKE '202102%'
UNION ALL
SELECT 'KNVV' Tabela, left(ERDAT,6) ANOMES , COUNT(1) TOTAL_REGISTROS FROM SGBODS.pm.KNVV GROUP BY left(ERDAT,6)-- ERDAT LIKE '202102%'
UNION ALL
SELECT 'KNVP' Tabela, left(ERDAT,6) ANOMES , COUNT(1) TOTAL_REGISTROS FROM SGBODS.pm.KNVP A 
INNER JOIN SGBODS.pm.KNVV B
ON A.[MANDT] = B.[MANDT]
AND A.[KUNNR] = B.[KUNNR]
AND A.[VKORG] = B.[VKORG]
AND A.[VTWEG] = B.[VTWEG]
AND A.[SPART] = B.[SPART]
GROUP BY left(ERDAT,6)
UNION ALL
SELECT 'VBRP' Tabela, left(ERDAT,6) ANOMES , COUNT(1) TOTAL_REGISTROS FROM SGBODS.pm.VBRP GROUP BY left(ERDAT,6) -- ERDAT LIKE '202101%'
UNION ALL
SELECT 'VBRK' Tabela, left(ERDAT,6) ANOMES , COUNT(1) TOTAL_REGISTROS FROM SGBODS.pm.VBRK GROUP BY left(ERDAT,6)-- ERDAT LIKE '202101%'
UNION ALL
SELECT '/ICO/MO_RUP' Tabela, left(PRSDT,6)  ANOMES, COUNT(1) TOTAL_REGISTROS FROM SGBODS.pm.[/ICO/MO_RUP] GROUP BY left(PRSDT,6) -- PRSDT LIKE '202101%'
UNION ALL
SELECT '/ICO/MO_RUK' Tabela, left(ERDAT,6) ANOMES , COUNT(1) TOTAL_REGISTROS  FROM SGBODS.pm.[/ICO/MO_RUK] GROUP BY left(ERDAT,6) -- ERDAT LIKE '202101%'
UNION ALL
SELECT 'J_1BNFDOC' Tabela, left(PSTDAT,6) ANOMES , COUNT(1) TOTAL_REGISTROS  FROM SGBODS.pm.J_1BNFDOC GROUP BY left(PSTDAT,6) -- PSTDAT LIKE '202101%'
--SELECT 'J_1BNFLIN' Tabela, ANOMES , COUNT(1) TOTAL_REGISTROS FROM SGBODS.pm.J_1BNFLIN 
UNION ALL
SELECT 'LIPS' Tabela, LEFT(ERDAT,6) ANOMES , COUNT(1) TOTAL_REGISTROS FROM SGBODS.pm.LIPS GROUP BY LEFT(ERDAT,6)-- ERDAT LIKE '202105%'
UNION ALL
SELECT 'LIKP' Tabela, LEFT(ERDAT, 6) ANOMES , COUNT(1) TOTAL_REGISTROS FROM SGBODS.pm.LIKP GROUP BY LEFT(ERDAT, 6) -- ERDAT LIKE '202101%'
UNION ALL
SELECT 'MKPF' Tabela, LEFT(CPUDT,6) ANOMES , COUNT(1) TOTAL_REGISTROS FROM SGBODS.pm.MKPF GROUP BY LEFT(CPUDT,6)	-- CPUDT
UNION ALL
SELECT 'MSEG' Tabela, LEFT(CPUDT_MKPF,6) ANOMES , COUNT(1) TOTAL_REGISTROS FROM SGBODS.pm.MSEG GROUP BY LEFT(CPUDT_MKPF,6)	-- CPUDT_MKPF
UNION ALL
SELECT 'BKPF' Tabela, LEFT(CPUDT,6) ANOMES, COUNT(1) TOTAL_REGISTROS  FROM SGBODS.pm.BKPF GROUP BY LEFT(CPUDT,6)	-- CPUDT
UNION ALL
SELECT 'BSEG' Tabela, LEFT(BZDAT,6) ANOMES , COUNT(1) TOTAL_REGISTROS FROM SGBODS.pm.BSEG GROUP BY LEFT(BZDAT,6) 	-- BZDAT
UNION ALL
SELECT 'VBAP' Tabela, LEFT(ERDAT,6) ANOMES , COUNT(1) TOTAL_REGISTROS FROM SGBODS.pm.VBAP GROUP BY LEFT(ERDAT,6) -- ERDAT LIKE '20210211%'
UNION ALL
SELECT 'VBAK' Tabela, LEFT(AUDAT,6) ANOMES  , COUNT(1) TOTAL_REGISTROS FROM SGBODS.pm.VBAK GROUP BY LEFT(AUDAT,6)-- AUDAT LIKE '20210101%'

) a 

-----------------------------------------------------------------------------------


SELECT 
Tabela,
[202101] as '202101',
[202102] as '202102',
[202103] as '202103',
[202104] as '202104',
[202105] as '202105',
[202106] as '202106',
[202107] as '202107',
[202108] as '202108',
[202109] as '202109',
[202110] as '202110'
FROM
(

select *
from #tmpPM with(nolock)
	
) as SourceTable
PIVOT
(
	MAX(TOTAL_REGISTROS)
FOR ANOMES IN (
[202101],
[202102],
[202103],
[202104],
[202105],
[202106],
[202107],
[202108],
[202109],
[202110])
) AS PivotTable