DECLARE @USUARIO VARCHAR(100) = 'brsgdb-compass3'
,@SENHA VARCHAR(100) = '8fdKJl3$nlNv3049jsKK'
,@SCHEMA VARCHAR(100) = 'compass'
,@CMD01  VARCHAR(500)
,@CMD02  VARCHAR(500)
,@CMD03  VARCHAR(500)

SET @CMD01 = 'CREATE LOGIN [' + @USUARIO + '] WITH PASSWORD = ' + CHAR(39) + @SENHA + CHAR(39) + ';'  

PRINT(@CMD01)

SET @CMD02 = 'CREATE USER [' + @USUARIO + '] FOR LOGIN [' + @USUARIO + '] WITH DEFAULT_SCHEMA = ' + @SCHEMA  + ';'

PRINT(@CMD02)

SET @CMD03 = 'GRANT CONNECT TO [' + @USUARIO + '];'

PRINT(@CMD03)

--BEGIN TRAN 

EXEC(@CMD01)
EXEC(@CMD02)
EXEC(@CMD03)

--COMMIT 

--GRANT SELECT,INSERT,DELETE, UPDATE ON OBJECT::schema.tabela TO [usuario];