IF EXISTS ( SELECT 1 FROM SYS.tables WHERE NAME = 'GABRIEL' )
DROP TABLE sch_ods.GABRIEL
GO

CREATE TABLE sch_ods.GABRIEL
(
ID INT NOT NULL IDENTITY(1,1)
, IDADE INT NOT NULL 
, NOME VARCHAR(200)
, id_cargo INT NOT NULL
, data datetime not null
, sexo char(1) not null 
, salario decimal(18,4) 
, Desconto as (salario *1.4) PERSISTED
, CPF BIGINT NOT NULL
)
GO

ALTER TABLE sch_ods.GABRIEL ADD CONSTRAINT [PK_TB_GABRIEL] PRIMARY KEY (ID)
GO

ALTER TABLE sch_ods.GABRIEL ADD CONSTRAINT [DF] DEFAULT GETDATE() FOR DATA

ALTER TABLE sch_ods.GABRIEL ADD CONSTRAINT [CK] CHECK (SEXO IN ('M','F'))

ALTER TABLE sch_ods.GABRIEL ADD CONSTRAINT [UK] UNIQUE (CPF)

IF EXISTS ( SELECT 1 FROM SYS.tables WHERE NAME = 'TB_CARGOGABRIEL' )
DROP TABLE sch_ods.TB_CARGOGABRIEL
GO

CREATE TABLE SCH_ODS.TB_CARGOGABRIEL
(ID_CARGO INT NOT NULL
, DESCRICAO VARCHAR(100))
GO

ALTER TABLE sch_ods.TB_CARGOGABRIEL ADD CONSTRAINT [PK_TB_TB_CARGOGABRIEL] PRIMARY KEY (ID_CARGO)
GO

ALTER TABLE SCH_ODS.GABRIEL ADD CONSTRAINT [FK_CARGO] FOREIGN KEY (id_cargo) REFERENCES sch_ods.TB_CARGOGABRIEL (ID_CARGO)
GO

CREATE NONCLUSTERED INDEX [IX_CPF] ON sch_ods.GABRIEL (CPF ASC)

CREATE NONCLUSTERED INDEX [IX_NOME_CPF] ON sch_ods.GABRIEL (NOME ASC,CPF ASC)


ALTER INDEX [IX_NOME_CPF] on sch_ods.GABRIEL REBUILD PARTITION = ALL 
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,
SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE)

ALTER INDEX [PK_TB_GABRIEL] on sch_ods.GABRIEL REBUILD PARTITION = ALL 
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,
SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE)

--SP_HELP 'sch_ods.GABRIEL'

/*

1 - TABELA SIMPLES ( SEM PK, SEM DEFAULT, SEM UNIQUE, SEM IDENTITY)
2 - ALTERAÇÃO PARA INCLUSÃO DO SCHEMA
3 - CRIACAO DE PK
4 - CRIACAO DE FK
5 - CRIACAO DE DEFAULT
6 - CRIACAO DE CHECK CONSTRAINT
7 - COMPUTED COLUMN
8 - UNIQUE

*/